#!/usr/bin/env npx tsx
/**
 * Embeds the ELIZA CLI bundle as a string constant.
 * Run after esbuild creates the bundle.
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const bundlePath = path.join(__dirname, "..", "dist", "agents", "eliza", "cli.bundle.js")
const outputPath = path.join(__dirname, "..", "src", "agents", "eliza", "bundle-content.ts")

if (!fs.existsSync(bundlePath)) {
  console.error(`Bundle not found at ${bundlePath}. Run 'npm run build:eliza-bundle' first.`)
  process.exit(1)
}

const bundleContent = fs.readFileSync(bundlePath, "utf-8")

// Escape backticks and ${} for template literal
const escaped = bundleContent
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${")

const output = `/**
 * ELIZA CLI bundle content - auto-generated, do not edit.
 * Generated by scripts/embed-eliza-bundle.ts
 */

// eslint-disable-next-line
export const ELIZA_BUNDLE_CONTENT = \`${escaped}\`
`

fs.writeFileSync(outputPath, output)
console.log(`Embedded ELIZA bundle (${bundleContent.length} bytes) into ${outputPath}`)
