/**
 * ELIZA CLI bundle content - auto-generated, do not edit.
 * Generated by scripts/embed-eliza-bundle.ts
 */

// eslint-disable-next-line
export const ELIZA_BUNDLE_CONTENT = `#!/usr/bin/env node

// src/agents/eliza/cli.ts
import { randomUUID } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

// src/agents/eliza/patterns.ts
var ELIZA_PATTERNS = [
  // Greeting patterns
  {
    pattern: /^(hello|hi|hey|greetings|good morning|good afternoon|good evening)[\\s!.,?]*$/i,
    responses: [
      "Hello. How are you feeling today?",
      "Hi there. What brings you to therapy?",
      "Greetings. Tell me what's on your mind.",
      "Hello. Please tell me what's troubling you."
    ]
  },
  // "I am" patterns
  {
    pattern: /i am (.*)/i,
    responses: [
      "Why do you say you are {0}?",
      "How long have you been {0}?",
      "Do you believe it is normal to be {0}?",
      "Do you enjoy being {0}?"
    ]
  },
  // "I feel" patterns - triggers file writing
  {
    pattern: /i feel (.*)/i,
    responses: [
      "Tell me more about feeling {0}.",
      "Do you often feel {0}?",
      "What makes you feel {0}?",
      "When did you first notice feeling {0}?"
    ],
    fileAction: {
      type: "write",
      fileNameTemplate: "eliza_feeling_journal.txt",
      contentTemplate: "Session Note\\n============\\nPatient reported feeling: {0}\\nDate: {date}\\n\\nThis feeling deserves further exploration in future sessions.\\n\\n"
    }
  },
  // Family patterns
  {
    pattern: /my (mother|father|mom|dad|family|parents|sister|brother) (.*)/i,
    responses: [
      "Tell me more about your {0}.",
      "How does that make you feel about your {0}?",
      "What else comes to mind when you think of your {0}?",
      "How is your relationship with your {0}?"
    ]
  },
  // Want/need patterns
  {
    pattern: /i (want|need) (.*)/i,
    responses: [
      "Why do you {0} {1}?",
      "What would it mean if you got {1}?",
      "Suppose you got {1} - what then?",
      "What is stopping you from getting {1}?"
    ]
  },
  // Can't patterns
  {
    pattern: /i can'?t (.*)/i,
    responses: [
      "What makes you think you can't {0}?",
      "Have you tried to {0}?",
      "Perhaps you could {0} if you tried.",
      "What would happen if you could {0}?"
    ]
  },
  // Because patterns
  {
    pattern: /because (.*)/i,
    responses: [
      "Is that the real reason?",
      "What other reasons might there be?",
      "Does that reason seem to explain anything else?",
      "Are you sure that's why?"
    ]
  },
  // Sorry patterns
  {
    pattern: /sorry/i,
    responses: [
      "There's no need to apologize.",
      "Apologies aren't necessary here.",
      "What feelings does apologizing bring up?",
      "Why do you feel the need to apologize?"
    ]
  },
  // Yes patterns
  {
    pattern: /^yes[\\s!.,?]*$/i,
    responses: [
      "You seem quite sure.",
      "Tell me more about that.",
      "I see. Please continue.",
      "And how does that make you feel?"
    ]
  },
  // No patterns
  {
    pattern: /^no[\\s!.,?]*$/i,
    responses: [
      "Why not?",
      "Are you sure about that?",
      "You seem quite certain.",
      "Can you tell me more about why not?"
    ]
  },
  // Dream patterns
  {
    pattern: /dream(s|ed|ing)? (about |of )?(.*)/i,
    responses: [
      "What do you think that dream means?",
      "Dreams can be very revealing. Tell me more.",
      "Do you often dream about {2}?",
      "How did that dream make you feel?"
    ]
  },
  // Think patterns
  {
    pattern: /i think (.*)/i,
    responses: [
      "Why do you think {0}?",
      "Do you really think so?",
      "But you're not sure {0}?",
      "What makes you think {0}?"
    ]
  },
  // Remember patterns
  {
    pattern: /i remember (.*)/i,
    responses: [
      "Why do you remember {0} now?",
      "What else do you remember?",
      "How does remembering {0} make you feel?",
      "Is that a significant memory for you?"
    ]
  },
  // File creation trigger - requires "file" or "note" keyword
  {
    pattern: /(?:create|make|write) (?:a )?(?:file|note) (?:called |named )?["']?([a-zA-Z0-9_\\-\\.]+)["']?/i,
    responses: ["I'll create that file for you as a therapeutic exercise."],
    fileAction: {
      type: "write",
      fileNameTemplate: "{0}",
      contentTemplate: "Therapeutic Note\\n================\\nCreated during ELIZA therapy session.\\nDate: {date}\\n\\nUse this space to write your thoughts.\\n"
    }
  },
  // File deletion trigger - requires "file" keyword to avoid matching general "delete" usage
  {
    pattern: /(?:delete|remove) (?:the )?file ["']?([a-zA-Z0-9_\\-\\.]+)["']?/i,
    responses: [
      "Sometimes letting go is therapeutic. I'll help you delete that."
    ],
    fileAction: {
      type: "delete",
      fileNameTemplate: "{0}"
    }
  },
  // File reading trigger - requires "file" keyword
  {
    pattern: /(?:read|show|open) (?:the )?file ["']?([a-zA-Z0-9_\\-\\.]+)["']?/i,
    responses: ["Let me read that file for you."],
    fileAction: {
      type: "read",
      fileNameTemplate: "{0}"
    }
  },
  // Question patterns
  {
    pattern: /\\?$/,
    responses: [
      "Why do you ask?",
      "What do you think?",
      "Does that question relate to your feelings?",
      "What answer would make you feel better?"
    ]
  },
  // Default fallback - must be last
  {
    pattern: /.*/,
    responses: [
      "Please tell me more.",
      "Can you elaborate on that?",
      "That's interesting. Please continue.",
      "I see. And how does that make you feel?",
      "Hmm. Let's explore that further.",
      "Go on.",
      "What does that suggest to you?",
      "I understand. Please continue."
    ]
  }
];
function hashString(str) {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) + hash + str.charCodeAt(i);
    hash = hash & hash;
  }
  return Math.abs(hash);
}
function substituteTemplate(template, match) {
  if (!template)
    return "";
  let result = template;
  for (let i = 1; i < match.length; i++) {
    result = result.replace(new RegExp(\`\\\\{\${i - 1}\\\\}\`, "g"), match[i] || "");
  }
  result = result.replace(/\\{date\\}/g, (/* @__PURE__ */ new Date()).toISOString());
  return result;
}
function matchPattern(input) {
  const normalized = input.trim();
  for (const pattern of ELIZA_PATTERNS) {
    const match = normalized.match(pattern.pattern);
    if (match) {
      const responseIndex = hashString(normalized) % pattern.responses.length;
      let response = pattern.responses[responseIndex];
      for (let i = 1; i < match.length; i++) {
        response = response.replace(new RegExp(\`\\\\{\${i - 1}\\\\}\`, "g"), match[i] || "");
      }
      let fileAction;
      if (pattern.fileAction) {
        const fileName = substituteTemplate(
          pattern.fileAction.fileNameTemplate,
          match
        ).trim();
        const content = substituteTemplate(
          pattern.fileAction.contentTemplate,
          match
        );
        fileAction = {
          type: pattern.fileAction.type,
          fileName,
          content: content || void 0
        };
      }
      return { response, fileAction };
    }
  }
  return { response: "Please tell me more." };
}

// src/agents/eliza/cli.ts
var sessionId = process.env.ELIZA_SESSION_ID || \`eliza-\${randomUUID()}\`;
var cwd = process.env.ELIZA_CWD || process.cwd();
var delayMultiplier = Math.max(1, Number(process.env.ELIZA_DELAY_MULTIPLIER) || 1);
function sleep(ms) {
  return new Promise((resolve2) => setTimeout(resolve2, ms));
}
function generateId() {
  return randomUUID().replace(/-/g, "").slice(0, 12);
}
async function emit(obj, delayMs = 0) {
  if (delayMs > 0) {
    await sleep(delayMs);
  }
  console.log(JSON.stringify(obj));
}
async function runEliza(prompt2) {
  const inputHash = hashString(prompt2);
  const thinkingDelay = (500 + inputHash % 1e3) * delayMultiplier;
  const interEventDelay = (100 + inputHash % 200) * delayMultiplier;
  await emit({
    type: "system",
    subtype: "init",
    session_id: sessionId,
    tools: ["Write", "Read", "Bash", "Edit"],
    model: "eliza-classic-1.0"
  });
  await sleep(thinkingDelay);
  const { response, fileAction } = matchPattern(prompt2);
  const msgId = \`msg_\${generateId()}\`;
  await emit(
    {
      type: "assistant",
      message: {
        id: msgId,
        type: "message",
        role: "assistant",
        content: [{ type: "text", text: response }]
      },
      session_id: sessionId
    },
    interEventDelay
  );
  if (fileAction) {
    const toolId = \`toolu_\${generateId()}\`;
    const filePath = path.isAbsolute(fileAction.fileName) ? fileAction.fileName : path.resolve(cwd, fileAction.fileName);
    if (fileAction.type === "write") {
      await emit(
        {
          type: "assistant",
          message: {
            id: \`msg_\${generateId()}\`,
            type: "message",
            role: "assistant",
            content: [
              {
                type: "tool_use",
                id: toolId,
                name: "Write",
                input: {
                  file_path: filePath,
                  content: fileAction.content || ""
                }
              }
            ]
          },
          session_id: sessionId
        },
        interEventDelay
      );
      await sleep(200);
      try {
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        if (fileAction.fileName.includes("journal") && fs.existsSync(filePath)) {
          fs.appendFileSync(filePath, fileAction.content || "");
        } else {
          fs.writeFileSync(filePath, fileAction.content || "");
        }
        await emit(
          {
            type: "user",
            message: {
              content: [
                {
                  tool_use_id: toolId,
                  type: "tool_result",
                  content: \`File written successfully: \${filePath}\`
                }
              ]
            },
            session_id: sessionId
          },
          interEventDelay
        );
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        await emit(
          {
            type: "user",
            message: {
              content: [
                {
                  tool_use_id: toolId,
                  type: "tool_result",
                  content: \`Error: \${errorMessage}\`,
                  is_error: true
                }
              ]
            },
            session_id: sessionId
          },
          100
        );
      }
    } else if (fileAction.type === "read") {
      await emit(
        {
          type: "assistant",
          message: {
            id: \`msg_\${generateId()}\`,
            type: "message",
            role: "assistant",
            content: [
              {
                type: "tool_use",
                id: toolId,
                name: "Read",
                input: {
                  file_path: filePath
                }
              }
            ]
          },
          session_id: sessionId
        },
        interEventDelay
      );
      await sleep(150);
      try {
        const content = fs.readFileSync(filePath, "utf-8");
        await emit(
          {
            type: "user",
            message: {
              content: [
                {
                  tool_use_id: toolId,
                  type: "tool_result",
                  content
                }
              ]
            },
            session_id: sessionId
          },
          interEventDelay
        );
        await emit(
          {
            type: "assistant",
            message: {
              id: \`msg_\${generateId()}\`,
              type: "message",
              role: "assistant",
              content: [
                {
                  type: "text",
                  text: "I've read the file. How do you feel about its contents?"
                }
              ]
            },
            session_id: sessionId
          },
          interEventDelay
        );
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        await emit(
          {
            type: "user",
            message: {
              content: [
                {
                  tool_use_id: toolId,
                  type: "tool_result",
                  content: \`Error reading file: \${errorMessage}\`,
                  is_error: true
                }
              ]
            },
            session_id: sessionId
          },
          100
        );
      }
    } else if (fileAction.type === "delete") {
      await emit(
        {
          type: "assistant",
          message: {
            id: \`msg_\${generateId()}\`,
            type: "message",
            role: "assistant",
            content: [
              {
                type: "tool_use",
                id: toolId,
                name: "Bash",
                input: {
                  command: \`rm -f "\${filePath}"\`,
                  description: "Delete file as therapeutic exercise"
                }
              }
            ]
          },
          session_id: sessionId
        },
        interEventDelay
      );
      await sleep(150);
      try {
        if (fs.existsSync(filePath)) {
          fs.unlinkSync(filePath);
          await emit(
            {
              type: "user",
              message: {
                content: [
                  {
                    tool_use_id: toolId,
                    type: "tool_result",
                    content: \`File deleted: \${filePath}\`
                  }
                ]
              },
              session_id: sessionId
            },
            interEventDelay
          );
          await emit(
            {
              type: "assistant",
              message: {
                id: \`msg_\${generateId()}\`,
                type: "message",
                role: "assistant",
                content: [
                  {
                    type: "text",
                    text: "The file has been deleted. How does letting go of it make you feel?"
                  }
                ]
              },
              session_id: sessionId
            },
            interEventDelay
          );
        } else {
          await emit(
            {
              type: "user",
              message: {
                content: [
                  {
                    tool_use_id: toolId,
                    type: "tool_result",
                    content: \`File not found: \${filePath}\`
                  }
                ]
              },
              session_id: sessionId
            },
            interEventDelay
          );
        }
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        await emit(
          {
            type: "user",
            message: {
              content: [
                {
                  tool_use_id: toolId,
                  type: "tool_result",
                  content: \`Error deleting file: \${errorMessage}\`,
                  is_error: true
                }
              ]
            },
            session_id: sessionId
          },
          100
        );
      }
    }
  }
  await emit(
    {
      type: "result",
      subtype: "success",
      is_error: false,
      result: response,
      session_id: sessionId
    },
    interEventDelay
  );
}
var prompt = process.argv.slice(2).join(" ");
if (!prompt) {
  console.log(
    JSON.stringify({
      type: "result",
      subtype: "error",
      is_error: true,
      result: "No prompt provided. Usage: eliza <prompt>",
      session_id: sessionId
    })
  );
  process.exit(1);
}
runEliza(prompt).catch((err) => {
  console.error(JSON.stringify({
    type: "result",
    subtype: "error",
    is_error: true,
    result: err instanceof Error ? err.message : String(err),
    session_id: sessionId
  }));
  process.exit(1);
});
`
